'use strict';

/**
 * review router - custom routes only
 * Default CRUD routes are auto-generated by Strapi
 */

module.exports = {
  routes: [
    {
      method: 'GET',
      path: '/reviews/my',
      handler: 'review.myReviews',
      config: {
        auth: false,
        policies: [],
        middlewares: [],
      },
    },
  ],
};
